let libros = {
    lista: [
        {
           titulo:
           autor:
           portada:
           descripcion: 
        }, 
        {
            titulo:
            autor:
            portada:
            descripcion: 
         },
         {
            titulo:
            autor:
            portada:
            descripcion: 
         },
         {
            titulo:
            autor:
            portada:
            descripcion: 
         }, 
         {
            titulo:
            autor:
            portada:
            descripcion: 
         }, 
         {
            titulo:
            autor:
            portada:
            descripcion: 
         }, 
         {
            titulo:
            autor:
            portada:
            descripcion: 
         }, 
         {
            titulo:
            autor:
            portada:
            descripcion: 
         }, 
         {
            titulo:
            autor:
            portada:
            descripcion: 
         },
    ],
};

module.exports = libros; 
